name: CI

on:
  schedule:
    - cron: "0 5 * * *" # Run daily at 5 AM UTC
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  validate-snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone Floresta repository
        run: |
          git clone https://github.com/getfloresta/Floresta.git

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build and run Snippet Checker
        env:
          CODE_DIR: ${{ github.workspace }}/Floresta
        run: |
          cd snippet-checker
          cargo build --release
          ./target/release/snippet_checker

  build-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mdbook
        run: |
          cargo install mdbook --version 0.4.45 --locked
          mdbook -V

      - name: Install mdbook-linkcheck
        run: |
          cargo install mdbook-linkcheck --locked
          mdbook-linkcheck -V

      - name: Install mdbook-quiz
        run: |
          cargo install mdbook-quiz --locked
          mdbook-quiz -V

      - name: Build Book
        run: |
          mdbook build
